-- Flight monitor schema.
--
-- Design notes:
--  * flight_offer is keyed on a deterministic fingerprint (airports + dates + airlines + flight
--    numbers + stops), so the same trip found by two providers is ONE row, not two. That is what
--    makes the price history comparable over time and across sources.
--  * offer_source holds the per-provider view of that one offer: its own price, its own booking
--    link, its own FX conversion. Duplicates across providers are visible instead of being lost.
--  * price_history is append-only. Nothing in the application updates or deletes a row here.
--  * Every timestamp is stored WITH TIME ZONE. The application never writes a naive local time.

CREATE TABLE search_run (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id           VARCHAR(64)  NOT NULL,
    started_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at       TIMESTAMP WITH TIME ZONE,
    queries_planned   INTEGER      NOT NULL DEFAULT 0,
    queries_executed  INTEGER      NOT NULL DEFAULT 0,
    offers_found      INTEGER      NOT NULL DEFAULT 0,
    offers_accepted   INTEGER      NOT NULL DEFAULT 0,
    offers_rejected   INTEGER      NOT NULL DEFAULT 0,
    alerts_sent       INTEGER      NOT NULL DEFAULT 0,
    status            VARCHAR(32)  NOT NULL,
    notes             VARCHAR(2000)
);

CREATE INDEX idx_search_run_trip_started ON search_run (trip_id, started_at DESC);

CREATE TABLE provider_run (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_run_id  BIGINT       NOT NULL REFERENCES search_run (id) ON DELETE CASCADE,
    provider_code  VARCHAR(32)  NOT NULL,
    query_summary  VARCHAR(255) NOT NULL,
    success        BOOLEAN      NOT NULL,
    error_message  VARCHAR(1000),
    offers_found   INTEGER      NOT NULL DEFAULT 0,
    elapsed_millis BIGINT       NOT NULL DEFAULT 0,
    executed_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_provider_run_search ON provider_run (search_run_id);
CREATE INDEX idx_provider_run_provider ON provider_run (provider_code, executed_at DESC);

CREATE TABLE flight_offer (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id                 VARCHAR(64)  NOT NULL,
    fingerprint             VARCHAR(64)  NOT NULL,

    origin_airport          VARCHAR(4)   NOT NULL,
    destination_airport     VARCHAR(4)   NOT NULL,
    departure_at            TIMESTAMP WITH TIME ZONE,
    arrival_at              TIMESTAMP WITH TIME ZONE,
    return_departure_at     TIMESTAMP WITH TIME ZONE,
    return_arrival_at       TIMESTAMP WITH TIME ZONE,

    airlines                VARCHAR(255),
    flight_numbers          VARCHAR(500),
    outbound_stops          INTEGER      NOT NULL DEFAULT 0,
    inbound_stops           INTEGER,
    longest_leg_minutes     INTEGER,
    layovers                VARCHAR(1000),
    airports_visited        VARCHAR(500),
    countries_visited       VARCHAR(500),

    baggage_known           BOOLEAN      NOT NULL DEFAULT FALSE,
    baggage_cabin_included  BOOLEAN,
    baggage_checked_pieces  INTEGER,
    baggage_description     VARCHAR(500),
    fare_class              VARCHAR(64),
    detail_level            VARCHAR(32)  NOT NULL,

    accepted                BOOLEAN      NOT NULL,
    rejection_reasons       VARCHAR(1000),
    warnings                VARCHAR(1000),
    price_band              VARCHAR(32),
    duration_band           VARCHAR(32),
    score                   NUMERIC(8,2),

    current_price_gbp       NUMERIC(12,2) NOT NULL,
    lowest_price_gbp        NUMERIC(12,2) NOT NULL,
    lowest_price_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    highest_price_gbp       NUMERIC(12,2) NOT NULL,
    previous_price_gbp      NUMERIC(12,2),

    first_seen_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    last_alerted_at         TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_flight_offer_fingerprint UNIQUE (trip_id, fingerprint)
);

CREATE INDEX idx_flight_offer_trip_price ON flight_offer (trip_id, accepted, current_price_gbp);
CREATE INDEX idx_flight_offer_trip_score ON flight_offer (trip_id, accepted, score DESC);
CREATE INDEX idx_flight_offer_last_seen ON flight_offer (last_seen_at DESC);

CREATE TABLE offer_source (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id          BIGINT        NOT NULL REFERENCES flight_offer (id) ON DELETE CASCADE,
    provider_code     VARCHAR(32)   NOT NULL,
    provider_offer_id VARCHAR(500),
    price_original    NUMERIC(12,2) NOT NULL,
    currency          VARCHAR(3)    NOT NULL,
    price_gbp         NUMERIC(12,2) NOT NULL,
    fx_rate           NUMERIC(18,8) NOT NULL,
    fx_retrieved_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    booking_url       VARCHAR(2000),
    search_url        VARCHAR(2000),
    observed_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_offer_source UNIQUE (offer_id, provider_code)
);

CREATE INDEX idx_offer_source_offer ON offer_source (offer_id);

CREATE TABLE price_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id       BIGINT        NOT NULL REFERENCES flight_offer (id) ON DELETE CASCADE,
    trip_id        VARCHAR(64)   NOT NULL,
    observed_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    price_gbp      NUMERIC(12,2) NOT NULL,
    price_original NUMERIC(12,2) NOT NULL,
    currency       VARCHAR(3)    NOT NULL,
    fx_rate        NUMERIC(18,8) NOT NULL,
    provider_code  VARCHAR(32)   NOT NULL
);

CREATE INDEX idx_price_history_offer ON price_history (offer_id, observed_at DESC);
CREATE INDEX idx_price_history_trip ON price_history (trip_id, observed_at DESC);

CREATE TABLE alert (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id           BIGINT        REFERENCES flight_offer (id) ON DELETE SET NULL,
    trip_id            VARCHAR(64)   NOT NULL,
    alert_type         VARCHAR(48)   NOT NULL,
    price_gbp          NUMERIC(12,2) NOT NULL,
    previous_price_gbp NUMERIC(12,2),
    delta_gbp          NUMERIC(12,2),
    delta_percent      NUMERIC(8,2),
    message            VARCHAR(4000) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    delivered          BOOLEAN       NOT NULL DEFAULT FALSE,
    delivery_error     VARCHAR(1000)
);

CREATE INDEX idx_alert_offer ON alert (offer_id, created_at DESC);
CREATE INDEX idx_alert_trip ON alert (trip_id, created_at DESC);

-- Paced monthly call counter that keeps metered free tiers from being overrun.
CREATE TABLE provider_usage (
    provider_code VARCHAR(32) NOT NULL,
    year_month    VARCHAR(7)  NOT NULL,
    calls         INTEGER     NOT NULL DEFAULT 0,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_provider_usage PRIMARY KEY (provider_code, year_month)
);
